### PR TITLE
Tower build ui

### PR DESCRIPTION
**Pull request by Milchreis**
Adds a basic build menu for build, upgrade or sell towers

### CODE REVIEW

**Comment by naofireblade** [comment]
Hovering the upgrade button should show the price for upgrading instead the price for a new tower behind the button.

**Comment by naofireblade** [comment]
Selling the tower should give back the money for the tower and his upgrades. Currently you only get the money for the last upgrade back.

**Comment by naofireblade** [comment]
The punishment factor for selling a tower should be 0.85 instead of 0.5. The levels must be balanced so that you can barely kill all enemies, otherwise it would be to easy :) . Selling a tower and getting back only half the investment would make it impossible to finish the level then.

**Comment by Milchreis** [comment]
Selling ratio is now defined as constant value in main.js with 0.85
IMHO this is to much returned money.

**Comment by naofireblade** [comment]
That looks better with each commit! I have three more usability points:
- the clicked position should be highlighted when the build ui is open so that the player can check if he builds on the correct position
- the upgrade button should be not there when the last tier is reached
- the selector should be not visible when the build ui is open *or* clicking on another position should open the build ui there

**Pull request merged**
